### PR TITLE
Add preprint citations

### PR DESCRIPTION
**Pull request by fred-atherden**
Added tests from the latest [preprint recs](https://jats4r.org/preprint-citations)

### CODE REVIEW

**Comment by hubgit** [comment]
The validator should be updated with these changes now.

**Comment by fred-atherden** [comment]
Thanks @hubgit  - just tested and seeing some discrepancies.

When validating [preprint-test.xml](https://github.com/JATS4R/jats-schematrons/blob/master/testfiles/preprint-test.xml) I would expect there to be 6 errors and 1 warning, but in the JSON from the validator I'm only seeing 3 errors and 1 warning.

Also the tests have `<name/>` and `<value-of/>` elements in their messages but these are not carried over in the output of the validator:
- Test message: `&lt;<name/> publication-type="preprint"> must include either an &lt;ext-link> or a &lt;pub-id>.`
- Expected: `<element-citation publication-type="preprint"> must include either an <ext-link> or a <pub-id>.` 
- Output: `< publication-type=\"preprint\"> must include either an <ext-link> or a <pub-id>.`

I can rewrite the tests to not include these if we don't expect to support this kind of thing.

**Comment by fred-atherden** [comment]
Also, a separate issue, when I validate [kwd-test.xml](https://github.com/JATS4R/jats-schematrons/blob/master/testfiles/kwd-test.xml) i see this in the output:
```json
"ignored": [
      {
        "assertionId": "",
        "context": "*[kwd-group]",
        "errorMessage": {
          "ignored": true,
          "errorMessage": "XPath parse error"
        },
        "patternId": "kwd-warnings",
        "simplifiedTest": null,
        "test": "$vanilla-kwd-group-count le 1",
        "type": "warning"
      }
    ],
```

I take it it's the `let` variable in the respective test which isn't being supported?
```xml
<let name="vanilla-kwd-group-count" value="count(kwd-group[not(@xml:lang) and not(@kwd-group-type)])"/>
```

I can rewrite the test if this is expected.

**Comment by hubgit** [comment]
Apologies, I updated the wrong repository - try again now at either https://jats-validator.onrender.com/ or https://validator.jats4r.org/ and you should see the expected results (although they're all shown as warnings rather than errors).

**Comment by fred-atherden** [comment]
Looks good, thanks :+1:

**Pull request merged**
